### ISSUE TITLE
部署问题

### ISSUE THREAD

**Issue by cfaha** [yhsj0919/music_api#1]
可以写一下如何部署嘛

**Comment by yhsj0919** [comment]
打包运行之后，启动服务即可，暂时测试过windows，android，
这个不是面向服务做的，那些功能是顺带的，主要目的是整理接口，
cookie功能没做全，wy的api合并了，但是方法没写全，实在太多了(api模式没啥问题)
自己用的话可以稍加整理，参考一下接口就好
